Time to do doc all the things!
chef-partners/chef-provisioning-vsphere pull request #27
Opened 2017-05-13 19:21 UTC by jjasghar

Starting to yardoc everything.

![image](https://cloud.githubusercontent.com/assets/810824/26028500/754f7c48-37e7-11e7-9736-95063b6f8045.png)

Signed-off-by: JJ Asghar <jj@chef.io>

2017-05-13 22:09 UTC, michaeltlombardi commented
Let me know if you'd like any help/review. Documentation is one of my passions - and I'm actively using the project, soooooo. 😅

2017-05-13 22:32 UTC, jjasghar commented
Awesome! Please don't hesitate to comment on the additions already. I doing my "best guess" at what everything is doing and would love another pair of 👀 s.

2017-05-13 23:05 UTC, michaeltlombardi requested changes
Minor typos and clarifications - overall, this helps me understand the code much better than I did a week ago. Thank you for all of your work on this project!

2017-05-13 23:05 UTC, michaeltlombardi commented on README.md
> +We have attempted to `TODO` markings. If you find one weather it's documentation or a feature, it's a great place to start helping out. `$ grep -r "TODO" lib/`
> one weather it's

Should be `,whether it's` I think?

2017-05-13 23:05 UTC, michaeltlombardi commented on lib/chef/provisioning/vsphere_driver/vm_helper.rb
> +    # @return [true] The port to connect to the VM weather Windows or *nix.
> weather Windows or *nix

Should this be `whether` or `either`?

2017-05-13 23:05 UTC, michaeltlombardi commented on lib/chef/provisioning/vsphere_driver/vm_helper.rb
> +    # @param [String] port Uses the port number to connect.
I'm not familiar here, but I would've expected `port` to be an integer instead of a string.

2017-05-13 23:05 UTC, michaeltlombardi commented on lib/chef/provisioning/vsphere_driver/vsphere_helpers.rb
> +  # A namespace to for vSphere Helpers
> namespace to for

Should this be `namespace to use for`, or something else?

2017-05-13 23:05 UTC, michaeltlombardi commented on lib/chef/provisioning/vsphere_driver/vsphere_helpers.rb
> +    # @param [String] folder the folder name for to look into.
Is it the final folder name, or the fully qualified folder? For example, `2012R2` or `Templates\Windows\2012R2`.

2017-05-13 23:05 UTC, michaeltlombardi commented on lib/chef/provisioning/vsphere_driver/vsphere_helpers.rb
> +    # @param [String] folder the folder name for to look into.
Sorry, I think this one is actually answered further along by `find_folder`.

2017-05-13 23:05 UTC, michaeltlombardi commented on lib/chef/provisioning/vsphere_driver/vsphere_helpers.rb
> +    # Finds the Network cards fro the VM
> cards fro the

Minor typo, I think.

2017-05-15 02:09 UTC, jjasghar commented
Ok, I think this is ready now.

2017-05-15 17:57 UTC, merged